version: '3.1'

services:
  db:
    container_name: urba_form_db_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urba_form
